"""Add english_level to User

Revision ID: 52c48f8c4c05
Revises: bae108acdba3
Create Date: 2026-06-11 14:44:43.979107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c48f8c4c05'
down_revision: Union[str, Sequence[str], None] = 'bae108acdba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('english_level', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'english_level')
    # ### end Alembic commands ###
