"""add_easiness_factor_to_userword

Revision ID: 7716452d1a39
Revises: bbbbf9e6eb47
Create Date: 2026-06-16 14:40:48.732925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7716452d1a39'
down_revision: Union[str, Sequence[str], None] = 'bbbbf9e6eb47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_words', sa.Column('easiness_factor', sa.Float(), nullable=True))
    op.execute("UPDATE user_words SET easiness_factor = 2.5")
    op.alter_column('user_words', 'easiness_factor', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_words', 'easiness_factor')
    # ### end Alembic commands ###
