"""Initial migration

Revision ID: bae108acdba3
Revises: 
Create Date: 2026-06-11 13:09:10.071545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae108acdba3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_words_id'), 'dictionary_words', ['id'], unique=False)
    op.create_index(op.f('ix_dictionary_words_word'), 'dictionary_words', ['word'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('user_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=False),
    sa.Column('next_review', sa.DateTime(), nullable=False),
    sa.Column('repetition_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_words_id'), 'user_words', ['id'], unique=False)
    op.create_index(op.f('ix_user_words_word'), 'user_words', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_words_word'), table_name='user_words')
    op.drop_index(op.f('ix_user_words_id'), table_name='user_words')
    op.drop_table('user_words')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dictionary_words_word'), table_name='dictionary_words')
    op.drop_index(op.f('ix_dictionary_words_id'), table_name='dictionary_words')
    op.drop_table('dictionary_words')
    # ### end Alembic commands ###
